CREATE SCHEMA IF NOT EXISTS lixozerodb_teste;

USE lixozerodb_teste;

CREATE TABLE IF NOT EXISTS fiscal(
  id INT NOT NULL,
  nome VARCHAR(100) NOT NULL,
  matricula VARCHAR(45) NULL DEFAULT NULL,
  codigo VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS autuado (
  id INT NOT NULL AUTO_INCREMENT,
  fiscal_id INT NULL DEFAULT NULL,
  `data` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cpfCnpj VARCHAR(14) NOT NULL UNIQUE,
  autor VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS camera (
  id INT NOT NULL,
  bairro VARCHAR(45) NOT NULL,
  zona VARCHAR(45) NOT NULL,
  `local` VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS endereco(
  id INT PRIMARY KEY AUTO_INCREMENT,
  autuado_id INT NOT NULL,
  estado VARCHAR(45) NOT NULL,
  cidade VARCHAR(45) NOT NULL,
  cep VARCHAR(45) NOT NULL,
  bairro VARCHAR(45) NULL DEFAULT NULL,
  logradouro VARCHAR(45) NULL DEFAULT NULL,
  numero VARCHAR(45) NULL DEFAULT NULL,
  complemento VARCHAR(100) NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS descarte (
  id INT NOT NULL AUTO_INCREMENT,
  momento DATETIME NOT NULL,
  proveniencia VARCHAR(45) NOT NULL,
  placa CHAR(7) NULL DEFAULT NULL,
  descricao VARCHAR(100) NULL DEFAULT NULL,
  `local` VARCHAR(100) NULL DEFAULT NULL,
  coordenada POINT NULL DEFAULT NULL,
  eInfracao TINYINT NULL DEFAULT '1',
  consultado TINYINT NULL DEFAULT '0',
  feito TINYINT NULL DEFAULT '0',
  tipoVeiculo VARCHAR(100) NULL DEFAULT NULL,
  fiscal_id INT NOT NULL,
  camera_id INT NULL DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS infracao (
  id INT NOT NULL AUTO_INCREMENT,
  fiscal_id INT NOT NULL,
  evento_id INT NOT NULL,
  autuado_id INT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS veiculo (
  id INT NOT NULL AUTO_INCREMENT,
  autuado_id INT NOT NULL,
  placa VARCHAR(45) NOT NULL,
  marcaModelo VARCHAR(100) NULL DEFAULT NULL,
  cor VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
);
